cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash # Travis's default version is 1.3.2, we need 1.4.2 for nohoist
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm install --global coveralls
install:
  - yarn install
language: node_js
node_js:
  - '10'
script:
  - yarn lint
  - yarn test:api
  - yarn test --silent --coverage --coverageReporters=text-lcov | coveralls ; test ${PIPESTATUS[0]} -eq 0
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc 2> /dev/null
  - yarn global add gitbook-cli
  - yarn update-docs --scope=abi,light.js
deploy:
  # - provider: script
  #   skip_cleanup: true
  #   script: ./scripts/lerna-publish.sh
  #   on:
  #     branch: master
  - provider: pages
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: gitbook # The directory to be pushed to gh-pages branch
    skip-cleanup: true
    on:
      branch: master
